### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method getCertificate on channel com.pichillilorenzo/flutter_inappwebview_6)

### ISSUE THREAD

**Issue by meshachodoom** [Lukiya/flutter_onedrive#9]
When webview opens for user to enter credentials and login and you try to enter an email address the page reloads again. This is the error returned in the logs.
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method getCertificate on channel com.pichillilorenzo/flutter_inappwebview_6)
E/flutter (26267): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter (26267): <asynchronous suspension>
E/flutter (26267): #1      InAppWebViewController.getCertificate (package:flutter_inappwebview/src/in_app_webview/in_app_webview_controller.dart:2133:10)
E/flutter (26267): <asynchronous suspension>
E/flutter (26267): #2      BaseWebViewState.initWebView.<anonymous closure> (package:oauth_webauth/src/base_web_view.dart:152:18)
E/flutter (26267): <asynchronous suspension>
E/flutter (26267):

**Comment by Lukiya** [comment]
I can't reproduce this issue on iOS, what device are you using?
Or you can try to find solution at [https://github.com/pichillilorenzo/flutter_inappwebview](https://github.com/pichillilorenzo/flutter_inappwebview)

**Comment by meshachodoom** [comment]
Samsung Galaxy A30s
